engines:
    duplication:
      enabled: true
      exclude_paths:
        - '**_test.go'
        - 'asset/asset.go'
        - 'asset/live.go'
    remark-int:
      enabled: true
      exclude_paths:
        - 'Readme.md'
    jacksonlinter:
      enabled: true
      exclude_paths:
        - '.vscode/**'
    revive:
      enabled: true
      exclude_paths:
        - 'asset/asset.go'
        - 'asset/live.go'
    coverage:
      enabled: true
      exclude_paths:
        - 'asset/asset.go'
        - 'asset/live.go'
    metrics:
      enabled: true
      exclude_paths:
        - 'asset/asset.go'
        - 'asset/live.go'
