engines:
    duplication:
      enabled: true
      exclude_paths:
        - '**_test.go'
    remark-int:
      enabled: true
      exclude_paths:
        - 'Readme.md'
    jacksonlinter:
      enabled: true
      exclude_paths:
        - '.vscode/**'
    revive:
      enabled: true
      exclude_paths:
        - 'common/assets.go'
        - 'common/live.go'
