engines:
  duplication:
    enabled: true
    exclude_paths:
      - '**'
  remark-int:
    enabled: true
    exclude_paths:
      - 'Readme.md'
      - 'GOALS.md'
      - '**_test.go'

exclude_paths:
  - 'assets/assets.go'
  - 'assets/live.go'
  - 'assets/src/**'
  - 'Readme.md'
  - 'GOALS.md'
  - '.idea/**'
  - '.vscode/**'
  - '.github/**'
