engines:
    duplication:
      enabled: true
      exclude_paths:
        - '**_test.go'
    remark-lint:
      enabled: true
      exclude_paths:
        - 'Readme.md'
    jacksonlinter:
      enabled: true
      exclude_paths:
        - '.vscode/**'
