project_name: Covey
before:
  hooks:
    - go mod download
    - go get github.com/omeid/go-resources/cmd/resources
    - resources -declare -package=asset -output=asset/asset.go -tag="\!live" -trim assets/ assets/*
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    flags:
      - '-trimpath'
    ldflags:
      - -s
      - -w
#    hooks:
#      post: upx {{ .Path }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: chabad360
    name: covey
  draft: true
signs:
  - artifacts: all
    args: [ "--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}" ]

