name: CI

on:
  push:
  pull_request:

jobs:
  info:
    name: Build Info
    runs-on: ubuntu-latest
    outputs:
      git-describe: ${{ steps.describe.outputs.describe }}
      tagged: ${{ steps.tagged.outputs.tagged }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: git describe
        id: describe
        run: DESCRIBE=$(git describe) echo "::set-output name=describe::${DESCRIBE}"

      - name: Is tagged release
        continue-on-error: true
        id: tagged
        run: git describe --exact-match; [ $? -eq 0 ] && TAGGED=1 || TAGGED=0; echo "::set-output name=tagged::${TAGGED}"

  cache:
    name: Build Cache
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2.1.3
        with:
          path: |
            ~/go
            ~/.cache/go-build
          #  ~/Library/Caches/go-build
          #  %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-
            
      - name: Get dependencies
        run: |
          go get github.com/t-yuki/gocover-cobertura github.com/omeid/go-resources/cmd/resources github.com/traefik/yaegi/cmd/yaegi
          go mod download

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: |
            ~/go
            ~/.cache/go-build
          #  ~/Library/Caches/go-build
          #  %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-tests-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-tests-
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-

      - name: Pack assets
        run: resources -declare -package=asset -output=asset/asset.go -tag="!live" -trim assets/ ./assets/*

      - name: Test
        if: always()
        run: go test -trimpath -v -tags=insecure -coverprofile=coverage.txt -json -covermode count `go list ./... | grep -v test` > test.json

      - name: Provide annotations from test
        if: always()
        uses: guyarb/golang-test-annotations@v0.3.0

#       - name: Upload coverage
#         if: always()
#         env:
#           CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
#         run: |
#           gocover-cobertura < coverage.txt > coverage.xml
#           bash <(curl -Ls https://coverage.codacy.com/get.sh) \
#             report --language Go --force-language -r coverage.xml
      - name: Upload coverage
        if: always()
        uses: brpaz/godacov-action@v1.1.1
        with:
          reportPath: 'coverage.txt'
          codacyToken: ${{ secrets.CODACY_PROJECT_TOKEN }}
          commitId: ${{ github.sha }}

  fossa:
    name: Fossa
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ^1.15

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go
            ~/.cache/go-build
          #  ~/Library/Caches/go-build
          #  %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-

      - name: Fossa Action
        uses: fossa-contrib/fossa-action@v1.1.3
        with:
          fossa-api-key: ${{ secrets.FOSSA_CLI_TOKEN }}

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'go'
        
      - uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: |
            ~/go
            ~/.cache/go-build
          #  ~/Library/Caches/go-build
          #  %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-

      - name: Build
        run: |
          go generate
          go build github.com/chabad360/covey

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  snapshot:
    name: Build Snapshot
    runs-on: ubuntu-latest
    if: always()
    needs: [ info, analyze, fossa, test ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2.1.3
        with:
          path: |
            ~/go
            ~/.cache/go-build
          #  ~/Library/Caches/go-build
          #  %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: snapshot-${{ needs.info.outputs.git-describe }}
          path: dist
          retention-days: 7

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ info, snapshot ]
    if: ${{ needs.info.outputs.tagged }} == 1
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3.0.2
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

  golangci:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
          only-new-issues: true