name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        go get github.com/t-yuki/gocover-cobertura

    - name: Build
      run: go build -trimpath -v github.com/chabad360/covey
      
    - name: Build Shell PLugin
      run: go build -trimpath -v -buildmode=plugin -o plugins/task/shell.so github.com/chabad360/covey/plugins/task/shell

    - name: Test
      continue-on-error: true
      run: go test -v -coverprofile=coverage.txt -covermode count ./...
    
    - name: Upload Coverage to Codacy
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        gocover-cobertura < coverage.txt > coverage.xml
        bash <(curl -Ls https://coverage.codacy.com/get.sh) \
          report --language Go --force-language -r coverage.xml
