name: GolangCI-Lint

on:
  push:
  pull_request:

jobs:
  golangci:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
          only-new-issues: true
