name: Snapshot Build

on:
  push:
  pull_request:

jobs:
  snapshot:
    environment: snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2.1.3
        with:
          path: |
            ~/go
            ~/.cache/go-build
          #  ~/Library/Caches/go-build
          #  %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: snapshot-${{ github.run }}-${{ github.sha }}
          path: dist
          retention-days: 7